services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: civic_reporter
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://dev:dev123@postgres:5432/civic_reporter
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin123
      S3_BUCKET: civic-reports
      JWT_SECRET: dev-secret-change-in-production
    depends_on:
      - postgres
      - minio
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    command: sh -c "./wait-for-it.sh postgres:5432 --timeout=60 --strict -- yarn migrate && ./wait-for-it.sh minio:9000 --timeout=60 --strict -- yarn seed && yarn dev"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://backend:3001
      VITE_MAPBOX_TOKEN: your-mapbox-token-here
      VITE_GOOGLE_MAPS_API_KEY: your-google-maps-api-key-here
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  minio_data:
  redis_data: